
-- Dodao 'ON DELETE CASCADE'
ALTER TABLE KORISNIK_ZIVOTINJA
DROP CONSTRAINT KOR_ZIV_FK_ZIV;


ALTER TABLE KORISNIK_ZIVOTINJA
ADD CONSTRAINT KOR_ZIV_FK_ZIV
FOREIGN KEY (ZIVOTINJA_ID)
REFERENCES ZIVOTINJA (ZIVOTINJA_ID)
ON DELETE CASCADE;

